@extends('layouts.landing')
@section('meta-description')
CEEK is the only comprehensive and secure content platform for all devices. Live an amazing VR Experiences enjoying VR Concerts, games and sports
@stop
@section('title')
<title>CEEK VR Terms of Use | CEEK</title>
@stop
@section('content')
	<main id="fullpage" class="privacy">
        <section class="section" id="package">
            <div class="container">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1">
                        <div class="content text-justify">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                	<p>Effective: January 2015</p>
                                	<p><strong>Overview:</strong></p>
									<p>Welcome to CEEK VR INC! We are a developer of virtual reality experiences streamed to mobile VR devices and other console, desktop virtual reality devices ("CEEK VR ready devices").</p>
									<p>These Terms of Use govern your use of our service. As used in these Terms of Use, " CEEK VR INC service," "our service" or "the service" means the service provided by CEEK VR SOFTWARE AND HARDWARE for discovering and experiencing virtual reality, including all features and functionalities, website, and user interfaces, as well as all content and software associated with our service.</p>
									<p><strong>Using the Software</strong></p>
									<p>As long as you comply with these Terms, you have the right to use the Software for your own personal noncommercial use. This license is for the sole purpose of enabling you to use and enjoy the Software, in the manner permitted by these Terms.</p>
									<p>When you download our Software from Google Play or other app store or distribution platform you acknowledge and agree that you must also comply with all applicable third party terms of service when using our software or applications.</p>
									<p><strong>Unauthorized Activities</strong></p>
									<ul>
										<li>You may NOT copy, modify, distribute, sell, or lease any part of the Software (including any content in the Software), nor may you decompile, disassemble, reverse engineer or attempt to extract the source code of the Software, unless laws prohibit those restrictions or you have our written permission.</li>
										<li>You may NOT make any Software (including any content in the Software) available on any internet site, network or file-sharing service; use the Software for any commercial purpose or for the benefit of any third party or in any manner not by these Terms.</li>
										<li>We reserve the right to investigate and prosecute violations of any of the above and involve and cooperate with law enforcement authorities in prosecuting anyone who violates these Terms.</li>
									</ul>
									<p><strong>Third Party Devices</strong></p>
									<p>Our Software is designed to provide additional functionality with certain third party virtual reality devices (“Devices”). You should carefully review the terms and conditions, health warnings and all setup and operating instructions for such Devices.  We’re not responsible or liable in any way for any personal injury, property damage, or any other issue you may have resulting from your use of a Device.</p>
									<p><strong>Privacy Policy</strong></p>
									<p>Personally identifying information is subject to our Privacy Policy, the terms of which are incorporated herein. Please review our Privacy Policy to understand our practices. Please refer to our Privacy Policy for information on how we collect, use and disclose information from our users.</p>
									<p><strong>Ownership</strong></p>
									<p>Our Software is protected by copyright, trademark, and other laws of the United States and foreign countries.  Except as expressly provided in these Terms, we (or our licensors) exclusively own all right, title and interest in and to the Software, including all associated intellectual property rights. You may not remove, alter or obscure any copyright, trademark, service mark or other proprietary rights notices incorporated in or accompanying the Software.  If you provide any suggestions, ideas, feedback, or recommendations to us regarding our Software (“Feedback”), you give us a worldwide, perpetual, irrevocable, fully-paid and royalty-free license to use and exploit that Feedback for any purpose and without any obligation to you.</p>
									<p><strong>Termination</strong></p>
									<p>If you breach any of the terms of these Terms, your license to use of the Software will terminate automatically.</p>
									<p><strong>Use of the Software is at Your Own Risk</strong></p>
									<p>Your access to and use of the Software is at your own risk.  By using the Software, you may view content that is provided by third parties, which may be objectionable, offensive, or otherwise inappropriate.  We are not responsible for such content, nor will we be liable in any way for any content made available via the Software.</p>
									<p>You understand and agree that the Software is provided to you “AS IS” and on an “AS AVAILABLE” basis.  Without limiting the foregoing, WE EXPLICITLY DISCLAIM ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR NON-INFRINGEMENT, AND ANY WARRANTIES ARISING OUT OF COURSE OF DEALING OR USAGE OF TRADE.  We make no warranty that the Software will meet your requirements or be available on an uninterrupted, secure, or error-free basis.</p>
									<p><strong>Limitation of Liability</strong></p>
									<p>WHEN PERMITTED BY LAW, WE WILL NOT BE RESPONSIBLE FOR ANY LOST PROFITS, REVENUES, OR DATA, FINANCIAL LOSSES OR ANY INDIRECT, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES. TO THE EXTENT PERMITTED BY LAW, OUR TOTAL LIABILITY FOR ANY CLAIM UNDER THESE TERMS, INCLUDING FOR ANY IMPLIED WARRANTIES, IS LIMITED TO THE AMOUNT YOU PAID US TO USE THE SOFTWARE AND IN NO EVENT WILL IT EXCEED $9.99. IN ALL CASES, WE WILL NOT BE LIABLE FOR ANY LOSS OR DAMAGE THAT IS NOT REASONABLY FORESEEABLE.</p>
									<p>Some jurisdictions do not allow the exclusion of certain warranties or the exclusion or limitation of liability for consequential or incidental damages, so the limitations above may not apply to you.</p>
									<p><strong>General</strong></p>
									<p>These Terms constitute the entire agreement between us with respect to the subject matter and supersedes and merges any prior proposals, understandings and contemporaneous communications. These Terms may be amended by us from time to time. If we make material changes to these Terms, we will notify you by posting the revised Terms or notifying you through the Software. Your continued use of the Software after the changes go into effect will constitute your agreement to such changes. These Terms will be governed by and construed in accordance with the laws of the State of California, without regard to or application of conflicts of law rules or principles. By using our Software you consent to personal jurisdiction and venue in the state and federal courts for Santa Clara County, California for any lawsuit arising from or relating to these Terms or the Software. YOU AGREE THAT YOU WILL ONLY BRING CLAIMS AGAINST US IN YOUR INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING. If any part of these Terms is determined to be invalid or unenforceable by a court of competent jurisdiction, that provision will be enforced to the maximum extent permissible and the remaining provisions of these Terms will remain in full force and effect.</p>
									<p><strong>Acceptance of Terms of Use</strong></p>
									<p>These Terms of Use, which include our Privacy Policy, End User License Agreement, terms on Cookies and Internet Advertising and, to the extent you use the social features, our Social Terms govern your use of the CEEK VR service. By using, visiting, or browsing the CEEK VR INC service, you accept and agree to these Terms of Use. If you do not agree to these Terms of Use, do not use the CEEK VR INC service. The CEEK VR INC service is provided by CEEK VR INC, or one of its affiliated companies. The CEEK VR INC company that is providing the service to you (referred to as " CEEK VR INC " in these Terms of Use) and with whom you are entering into this agreement, depends on the country from which you sign up for the CEEK VR INC service.</p>
									<p><strong>Changes to Terms of Use</strong></p>
									<p>CEEK VR INC may, from time to time, change these Terms of Use, including the Privacy Policy, EULA and Social Terms. Such revisions shall be effective immediately; provided however, for existing members, such revisions shall, unless otherwise stated, be effective 30 days after posting.</p>
									<p><strong>Communication Preferences</strong></p>
									<p>By using the CEEK VR INC service, you consent to receiving electronic communications from CEEK VR INC relating to your account. These communications may involve sending emails to your email address provided during registration, or posting communications on the CEEK VR INC service, or in the "Your Account" page and will include notices about your account (e.g., payment authorizations, change in password or Payment Method, confirmation e-mails and other transactional information) and are part of your relationship with CEEK VR INC. You agree that any notices, agreements, disclosures or other communications that we send to you electronically will satisfy any legal communication requirements, including that such communications be in writing. You should maintain copies of electronic communications by printing a paper copy or saving an electronic copy. You also consent to receiving certain other communications from us, such as newsletters about new CEEK VR INC features and content, special offers, promotional announcements and customer surveys via email or other methods.</p>
									<p><strong>Membership, Billing and Cancellation</strong></p>
									<ul class="list-unstyled">
										<li>Membership 
											<ul class="list-unstyled exts">
												<li>i.	Subscription Service. Should you elect a CEEK VR INC subscription membership, it will continue month-to-month unless and until you cancel your membership or we terminate it. You must have Internet access and provide us with a current, valid, accepted method of payment (as such may be updated from time to time, "Payment Method") to use the CEEK VR INC service. We will bill the monthly membership fee to your Payment Method. You must cancel your membership before it renews each month in order to avoid billing of the next month's membership fees to your Payment Method.</li>
												<li>ii.	Differing Memberships. We may offer a number of membership plans, including special promotional plans or memberships with differing conditions and limitations. Any materially different terms from those described in these Terms of Use will be disclosed at your sign-up or in other communications made available to you. You can find specific details regarding your membership with CEEK VR INC by visiting our website and clicking on the "Your Account" link. Some promotional memberships are offered by third parties in conjunction with the provision of their own products and services. We are not responsible for the products and services provided by such third parties. We reserve the right to modify, terminate or otherwise amend our offered membership plans.</li>
											</ul>
										</li>
										<li>Billing
											<ul class="list-unstyled exts">
												<li>iii.	Recurring Billing. By starting your CEEK VR membership and providing or designating a Payment Method, you authorize us to charge you a monthly membership fee at the then current rate, and any other charges you may incur in connection with your use of the CEEK VR service to your Payment Method. You acknowledge that the amount billed each month may vary from month to month for reasons that may include differing amounts due to promotional offers, including gift card redemption and promotional code redemption, and/or changing or adding a plan, and you authorize us to charge your Payment Method for such varying amounts, which may be billed monthly in one or more charges.</li>
												<li>iv.	Price Changes. We reserve the right to adjust pricing for our service or any components thereof in any manner and at any time as we may determine in our sole and absolute discretion. Except as otherwise expressly provided for in these Terms of Use, any price changes to your service will take effect following email notice to you. </li>
												<li>v.	Billing Cycle. The membership fee for our service will be billed at the beginning of the paying portion of your membership and each month thereafter unless and until you cancel your membership. We automatically bill your Payment Method each month on the calendar day corresponding to the commencement of your paying membership. Membership fees are fully earned upon payment. We reserve the right to change the timing of our billing, in particular, as indicated below, if your Payment Method has not successfully settled. In the event your paying membership began on a day not contained in a given month, we may bill your Payment Method on a day in the applicable month or such other day as we deem appropriate. For example, if you started your CEEK VR membership or became a paying member on January 31st, your next payment date is likely to be February 28th, and your Payment Method would be billed on that date. Your renewal date may change due to changes in your Membership. Visit our website and click on the "View billing details" link on the "Your Account" page to see the commencement date for your next renewal period. We may authorize your Payment Method in anticipation of membership or service-related charges. As used in these Terms of Use, "billing" shall indicate a charge, debit or other payment clearance, as applicable, against your Payment Method. Unless otherwise stated differently, month or monthly refers to your billing cycle.</li>
												<li>vi.	No Refunds. PAYMENTS ARE NONREFUNDABLE AND THERE ARE NO REFUNDS OR CREDITS FOR PARTIALLY USED PERIODS. Following any cancellation, however, you will continue to have access to the service through the end of your current billing period. At any time, and for any reason, we may provide a refund, discount, or other consideration to some or all of our members ("credits"). The amount and form of such credits, and the decision to provide them, are at our sole and absolute discretion. The provision of credits in one instance does not entitle you to credits in the future for similar instances, nor does it obligate us to provide credits in the future, under any circumstance.</li>
												<li>vii.	Payment Methods. You may edit your Payment Method information by visiting our website and clicking on the "Your Account" link, available at the top of the pages of the CEEK VR website. If a payment is not successfully settled, due to expiration, insufficient funds, or otherwise, and you do not edit your Payment Method information or cancel your account (see, "Cancellation" below), you remain responsible for any uncollected amounts and authorize us to continue billing the Payment Method, as it may be updated. This may result in a change to your payment billing dates. For certain Payment Methods, the issuer of your Payment Method may charge you a foreign transaction fee or other charges. Check with your Payment Method service provider for details.</li>
											</ul>
										</li>
										<li>Cancellation.										
											<p>You may cancel your CEEK VR INC membership at any time, and you will continue to have access to the CEEK VR service through the end of your monthly billing period. WE DO NOT PROVIDE REFUNDS OR CREDITS FOR ANY PARTIAL-MONTH MEMBERSHIP PERIODS OR UNWATCHED MOVIES OR TV SHOWS. To cancel, go to the "Your Account" page on our website and follow the instructions for cancellation. If you cancel your membership, your account will automatically close at the end of your current billing period. To see when your account will close, click "View billing details" on the "Your Account" page. If you signed up for CEEK VR INC using your account with a third party as a Payment Method, and wish to cancel your CEEK VR INC membership at any time, including during your free trial, you may need to do so through such third party, including by visiting your account with the applicable third party and turning off auto-renew, or unsubscribing from, the CEEK VR INC service through that third party. You may also find billing information about your CEEK VR INC membership by visiting your account with the applicable third party.</p>
										</li>
									</ul>
									<p><strong>CEEK VR Subscription Service</strong></p> 
									<ul class="list-unstyled exts">
										<li>b.	You must be 18 years of age, or the age of majority in your province, territory or country, to become a  premium subscriber of CEEK VR INC service. Individuals under the age of 18, or applicable age of majority, may utilize the service only with the involvement of a parent or legal guardian, under such person's account and otherwise subject to these Terms of Use.</li>
										<li>c.	The CEEK VR INC service, and any content viewed through our service, are for your personal and non-commercial use only. During your CEEK VR INC membership, we grant you a limited, non-exclusive, non-transferable, license to access the CEEK VR INC service and view movies and TV shows through the service on a streaming-only basis for that purpose. Except for the foregoing limited license, no right, title or interest shall be transferred to you. You agree not to use the service for public performances.</li>
										<li>d.	You may view a VR experience through the CEEK VR service primarily within the country in which you have established your account and only in geographic locations where we offer our service and have licensed such movie or TV show. The content that may be available to watch will vary by geographic location. CEEK VR will use technologies to verify your geographic location. THE NUMBER OF DEVICES ON WHICH YOU MAY SIMULTANEOUSLY WATCH IS LIMITED.</li>
										<li>e.	We continually update the CEEK VR INC service, including the content library. In addition, we continually test various aspects of our service, including our website, user interfaces, service levels, plans, promotional features, availability of movies and TV shows, delivery and pricing. We reserve the right to, and by using our service you agree that we may, include you in or exclude you from these tests without notice. We reserve the right in our sole and absolute discretion to make changes from time to time and without notice in how we offer and operate our service.</li>
										<li>f.	You agree to use the CEEK VR service, including all features and functionalities associated therewith, in accordance with all applicable laws, rules and regulations, or other restrictions on use of the service or content therein. You agree not to archive, download (other than through caching necessary for personal use), reproduce, distribute, modify, display, perform, publish, license, create derivative works from, offer for sale, or use (except as explicitly authorized in these Terms of Use) content and information contained on or obtained from or through the CEEK VR service without express written permission from CEEK VR and its licensors. You also agree not to: circumvent, remove, alter, deactivate, degrade or thwart any of the content protections in the CEEK VR service; use any robot, spider, scraper or other automated means to access the CEEK VR service; decompile, reverse engineer or disassemble any software or other products or processes accessible through the CEEK VR service; insert any code or product or manipulate the content of the CEEK VR service in any way; or, use any data mining, data gathering or extraction method. In addition, you agree not to upload, post, e-mail or otherwise send or transmit any material designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment associated with the CEEK VR service, including any software viruses or any other computer code, files or programs.</li>
										<li>g.	The availability of experiences will change from time to time, and from country to country. The quality of the display of the streaming movies & TV shows may vary from computer to computer, and device to device, and may be affected by a variety of factors, such as your location, the bandwidth available through and/or speed of your Internet connection. Please check with your Internet provider for information on possible Internet data usage charges. CEEK VR makes no representations or warranties about the quality of your watching experience. The time it takes to begin watching an experience will vary based on a number of factors, including your location, available bandwidth at the time, the movie or TV show you have selected and the configuration of your CEEK VR ready device.</li>
										<li>h.	CEEK VR streaming software is developed by, or for, CEEK VR and is designed to enable streaming of content from CEEK VR through CEEK VR ready devices. This software may vary by device and medium, and functionalities may also differ between devices. BY USING OUR SERVICE, YOU ACKNOWLEDGE AND AGREE TO THE END USER LICENSE AGREEMENT AND TO RECEIVE, WITHOUT FURTHER NOTICE OR PROMPTING, UPDATED VERSIONS OF THE CEEK VR AND RELATED THIRD-PARTY SOFTWARE. IF YOU DO NOT ACCEPT THE FOREGOING TERMS, DO NOT USE OUR SERVICE. WE DO NOT TAKE RESPONSIBILITY OR OTHERWISE WARRANT THE PERFORMANCE OF THESE DEVICES, INCLUDING THE CONTINUING COMPATIBILITY OF THE DEVICE WITH OUR SERVICE. By using our service, you agree to look solely to the entity that manufactured and/or sold you the device for any issues related to the device and its compatibility with the CEEK VR service. If your CEEK VR ready device is sold, lost or stolen, please deactivate the CEEK VR ready device. If you fail to log out or deactivate your device, subsequent users may access the CEEK VR service through your account and may be able to access certain of your account information.</li>
										<li>i.	We may terminate or restrict your use of our service, without compensation or notice if you are, or if we suspect that you are (i) in violation of any of these Terms of Use or (ii) engaged in illegal or improper use of the service.</li>
									</ul>
									<p><strong>Passwords & Account Access</strong></p> 
									<ul class="list-unstyled exts">
										<li>j.	The member who created the CEEK VR INC account and whose Payment Method is charged is referred to here as the Account Owner. The Account Owner has access and control over the CEEK VR INC account. The Account Owner's control is exercised through use of the Account Owner's password and therefore to maintain exclusive control, the Account Owner should not reveal the password to anyone. In addition, if the Account Owner wishes to prohibit others from contacting CEEK VR INC Customer Service and potentially altering the Account Owner's control, the Account Owner should not reveal the Payment Method details (e.g., last four digits of their credit or debit card, or their email address if they use PayPal) associated with their account. You are responsible for updating and maintaining the truth and accuracy of the information you provide to us relating to your account.</li>
										<li>k.	In order to provide you with ease of access to your account and to help administer the CEEK VR INC service, CEEK VR INC implements technology that enables us to recognize you as the Account Owner and provide you with direct access to your account without requiring you to retype any password or other user identification when you revisit the CEEK VR service, which includes accessing via CEEK VR INC ready devices or website.</li>
										<li>l.	You should be mindful of any communication requesting that you submit credit card or other account information. Providing your information in response to these types of communications can result in identity theft. Always access your sensitive account information by going directly to the CEEK VR INC website and not through a hyperlink in an email or any other electronic communication, even if it looks official. CEEK VR INC reserves the right to place any account on hold anytime with or without notification to the member in order to protect itself and its partners from what it believes to be fraudulent activity. CEEK VR INC is not obligated to credit or discount a membership for holds placed on the account by either a representative of CEEK VR INC or by the automated processes of CEEK VR INC.</li>
									</ul>
									<p>Disclaimers of Warranties and Limitations on Liability</p> 
									<ul class="list-unstyled exts">
										<li>m.	THE CEEK VR INC SERVICE AND ALL CONTENT AND SOFTWARE ASSOCIATED THEREWITH, OR ANY OTHER FEATURES OR FUNCTIONALITIES ASSOCIATED WITH THE CEEK VR SERVICE, ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITH ALL FAULTS AND WITHOUT WARRANTY OF ANY KIND. CEEK VR INC DOES NOT GUARANTEE, REPRESENT, OR WARRANT THAT YOUR USE OF THE CEEK VR INC SERVICE WILL BE UNINTERRUPTED OR ERROR-FREE. CEEK VR SPECIFICALLY DISCLAIMS LIABILITY FOR THE USE OF APPLICATIONS, CEEK VR READY DEVICES, AND CEEK VR INC SOFTWARE (INCLUDING THEIR CONTINUING COMPATIBILITY WITH OUR SERVICE).</li>
										<li>n.	TO THE EXTENT PERMISSIBLE UNDER APPLICABLE LAWS, IN NO EVENT SHALL CEEK VR INC, OR ITS SUBSIDIARIES OR ANY OF THEIR SHAREHOLDERS, DIRECTORS, OFFICERS, EMPLOYEES OR LICENSORS BE LIABLE (JOINTLY OR SEVERALLY) TO YOU FOR PERSONAL INJURY OR ANY SPECIAL, INCIDENTAL, INDIRECT OR CONSEQUENTIAL DAMAGES OF ANY KIND, OR ANY DAMAGES WHATSOEVER.</li>
										<li>o.	SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR CERTAIN TYPES OF DAMAGES. THEREFORE, SOME OF THE ABOVE LIMITATIONS IN THIS SECTION MAY NOT APPLY TO YOU.</li>
										<li>p.	NOTHING IN THESE TERMS OF USE SHALL AFFECT ANY NON-WAIVABLE STATUTORY RIGHTS THAT APPLY TO YOU. If any provision or provisions of these Terms of Use shall be held to be invalid, illegal, or unenforceable, the validity, legality and enforceability of the remaining provisions shall remain in full force and effect.</li>
									</ul>
									<p>2.	From time to time, other types of promotional codes may be available, including those provided as part of a third party promotion. Promotional codes may be redeemed as described in the specifics of the promotion. Gift cards and promotional codes can only be used once, cannot be redeemed for cash, and may be combined with other offers, including a free trial, subject to certain restrictions as determined by CEEK VR INC in its sole discretion. If you received a promotional code through an offer by a third party, additional conditions may apply.</p>

									<p><strong>Intellectual Property</strong></p>
									<ul class="list-unstyled exts">
										<li>a.	Copyright. The CEEK VR service, including all content provided on the CEEK VR service, is protected by copyright, trade secret or other intellectual property laws and treaties.</li>
										<li>b.	Trademarks. CEEK VR is a registered trademark of CEEK VR, Inc.</li>
										<li>c.	Patents. CEEK VR has patents that apply to our service. For information on CEEK VR patents visit www.uspto.gov.</li>
									</ul>
									<p><strong>Governing Law</strong></p>
									<ul class="list-unstyled exts">
										<li>d.	If you are a resident of Brazil, these Terms of Use shall be governed by and construed in accordance with the laws of Brazil.</li>
										<li>e.	For all other CEEK VR INC members, these Terms of Use shall be governed by and construed in accordance with the laws of the state of Delaware, U.S.A. without regard to conflict of laws provisions.</li>
										<li>f.	You may also be entitled to certain consumer protection rights under the laws of your local jurisdiction.</li>
									</ul>
									<p><strong>Third Party Applications</strong></p>
									<p>You may encounter third-party applications (including, without limitation, websites, widgets, software, or other software utilities) ("Application(s)") that interact with the CEEK VR INC service. These Applications may import data related to your CEEK VR INC account and activity and otherwise gather data from you. These Applications are provided solely as a convenience to you, and CEEK VR INC is not responsible for such Applications. SUCH APPLICATIONS ARE OWNED OR OPERATED BY THIRD PARTIES THAT ARE NOT RELATED TO WITH OR SPONSORED BY CEEK AND MAY NOT BE AUTHORIZED FOR USE WITH OUR SERVICE IN ALL COUNTRIES. USE OF AN APPLICATION IS AT YOUR OWN OPTION AND RISK.</p>

									<p><strong>Use of Information Submitted</strong></p>
									<p>CEEK VR INC is free to use any comments, information, ideas, concepts, reviews, or techniques or any other material contained in any communication you may send to us ("Feedback"), including responses to questionnaires or through postings to the CEEK VR INC service, including the CEEK VR INC website and user interfaces, worldwide and in perpetuity without further compensation, acknowledgement or payment to you for any purpose whatsoever including, but not limited to, developing, manufacturing and marketing products and creating, modifying or improving the CEEK VR service. In addition, you agree not to enforce any "moral rights" in and to the Feedback, to the extent permitted by applicable law. Please note CEEK VR INC does not accept unsolicited materials or ideas for movies or TV shows, and is not responsible for the similarity of any of its content or programming in any media to materials or ideas transmitted to CEEK VR INC. Should you send any unsolicited materials or ideas, you do so with the understanding that no additional consideration of any sort will be provided to you, and you are waiving any claim against CEEK VR INC and its affiliates regarding the use of such materials and ideas, even if material or an idea is used that is substantially similar to the material or idea you sent.</p>

									<p><strong>Customer Support</strong></p>
									<p>To find more information about our service and its features, or if you need assistance with your account, please visit CEEK VR INC Help Center. In certain instances, Customer Service may best be able to assist you by using support. In the event of any conflict between these Terms of Use and information provided by Customer Support or other portions of our website, these Terms of Use will control.</p>

									<p><strong>Contacting Us</strong></p>
									<p>Please <a href="mailto:support@ceek.com">contact us</a> if you have any questions about these Terms.</p>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
@stop